import sys
from crewai import Agent, Task, Crew, Process
from langchain_openai import ChatOpenAI
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import config


topic = "Shaming, critiquing, and the abrasive nature of human interactions in India: Exploring historical and contemporary perspectives, the impact of the European Enlightenment, and the role of power asymmetry in social dynamics"
num_guests = 5

os.environ["GROQ_API_KEY"] = config.GROQ_API_KEY

if __name__ == '__main__':
    llm = ChatOpenAI(
        openai_api_base="https://api.groq.com/openai/v1",
        openai_api_key=os.getenv("GROQ_API_KEY"),
        model_name="llama3-70b-8192"
    )

    host_info = {
        "name": "Rajeev Kumar",
        "email": "theideasandboxpodcast@gmail.com",
        "website": "tisb.world",
        "whatsapp": "3096797200"
    }

    content_generator = Agent(
        role="Content Generator",
        goal=f"Find interesting tidbits, historical facts, information from contemporary culture, and historical background related to the topic of shaming, critiquing, and the abrasive nature of human interactions in India, to make the podcast conversation engaging.",
        backstory=f"You are an AI assistant whose job is to find interesting content for the 'Bros Riffn' podcast about the topic of shaming, critiquing, and the abrasive nature of human interactions in India. Look for relevant information from various cultures around the world, including European, Australian, South American, and indigenous populations, on how they deal with shaming, correcting, critiquing, and respect for elders. Identify patterns among certain demographics and provide insights that can enrich the podcast discussion. Explore the historical and contemporary aspects of this topic, including the impact of the European Enlightenment on shaming culture and the role of power asymmetry in social interactions.",
        verbose=False,
        allow_delegation=False,
        llm=llm
    )

    content_critic = Agent(
        role="Content Critic",
        goal=f"Critique the content generated by the Content Generator based on its relevance to the topic of shaming, critiquing, and the abrasive nature of human interactions in India, its potential to make the podcast conversation interesting, and its accuracy and credibility.",
        backstory=f"You are an AI assistant whose job is to critique the content generated by the Content Generator. When evaluating the content, consider the following criteria: 1. Is the content relevant to the topic of shaming, critiquing, and the abrasive nature of human interactions in India, and does it have the potential to make the podcast conversation interesting? 2. Is the information accurate, credible, and sourced from reliable references? 3. Does the content provide diverse perspectives from different cultures and demographics, including insights from the European Enlightenment and its impact on shaming culture? Provide constructive feedback to help improve the quality and relevance of the generated content.",
        verbose=False,
        llm=llm
    )

    generate_content = Task(
        description=f"Find interesting tidbits, historical facts, information from contemporary culture, and historical background related to the topic of shaming, critiquing, and the abrasive nature of human interactions in India, to make the podcast conversation engaging. Explore the impact of the European Enlightenment on shaming culture and the role of power asymmetry in social interactions.",
        agent=content_generator,
        expected_output="A list of interesting content related to the topic, including tidbits, historical facts, contemporary cultural information, and historical background from various cultures and demographics, with a focus on the impact of the European Enlightenment and power asymmetry in social interactions.",
    )

    critique_content = Task(
        description=f"Critique the content generated by the Content Generator based on its relevance to the topic of shaming, critiquing, and the abrasive nature of human interactions in India, its potential to make the podcast conversation interesting, and its accuracy and credibility. Evaluate the content's inclusion of diverse perspectives from different cultures and demographics, including insights from the European Enlightenment and its impact on shaming culture.",
        agent=content_critic,
        expected_output=f"Constructive feedback on the generated content, evaluating its relevance to the topic of shaming, critiquing, and the abrasive nature of human interactions in India, potential to make the podcast conversation interesting, accuracy, credibility, and diversity of perspectives from different cultures and demographics, including insights from the European Enlightenment and its impact on shaming culture.",
    )
    crew = Crew(
        agents=[content_generator, content_critic],
        tasks=[generate_content, critique_content],
        verbose=1,
        process=Process.sequential
    )

    output = crew.kickoff()
    print(output)

    # Write the generated content to a file
    try:
        with open("/Users/rajeevkumar/Documents/BrosRiffn/podcast_content.txt", "w") as file:
            file.write(f"Topic: {topic}\n\n")
            file.write(output)
    except IOError as e:
        print(f"An error occurred while writing to the file: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")